# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xvYsUdXY9tvwAabBUqWWqmaehz42GdD
"""

# ════════════════════════════════════════════════════════════
# Cell 1 — 설치 및 Imports
# ════════════════════════════════════════════════════════════

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from datasets import load_dataset
from transformers import AutoTokenizer
from torch.nn.utils.rnn import pad_sequence
from tqdm import tqdm
import math
from sacrebleu import corpus_bleu

# ════════════════════════════════════════════════════════════
# Cell 2 — Attention
# ════════════════════════════════════════════════════════════
def scaled_dot_product_attention(Q, K, V, mask=None):
    d_k = Q.size(-1)
    score = Q @ K.transpose(-2, -1) / d_k ** 0.5
    if mask is not None:
        score = score.masked_fill(mask, -1e9)
    score = F.softmax(score, dim=-1)
    return score @ V


class MultiHeadAttention(nn.Module):
    def __init__(self, d_model=512, d_k=64, d_v=64, head=8):
        super().__init__()
        self.nhead = head
        self.d_k = d_k
        self.d_v = d_v
        self.W_Q = nn.Linear(d_model, head * d_k)
        self.W_K = nn.Linear(d_model, head * d_k)
        self.W_V = nn.Linear(d_model, head * d_v)
        self.W_O = nn.Linear(head * d_v, d_model)

    def forward(self, Q, K, V, mask=None):
        Q = self.W_Q(Q)
        K = self.W_K(K)
        V = self.W_V(V)
        B, S, _ = Q.size()
        _, S_K, _ = K.size()
        Q = Q.view(B, S, self.nhead, self.d_k).transpose(1, 2)
        K = K.view(B, S_K, self.nhead, self.d_k).transpose(1, 2)
        V = V.view(B, S_K, self.nhead, self.d_v).transpose(1, 2)
        O = scaled_dot_product_attention(Q, K, V, mask)
        O = O.transpose(1, 2).reshape(B, S, self.nhead * self.d_v)
        return self.W_O(O)

# ════════════════════════════════════════════════════════════
# Cell 3 — Model (Encoder / Decoder / Transformer)
# ════════════════════════════════════════════════════════════
def pos_encoder(emb, max_len, d_model):
    pos = torch.arange(max_len).unsqueeze(1)
    i = torch.arange(0, d_model, 2)
    div = 10000 ** (i / d_model)
    emb[:, 0::2] = torch.sin(pos / div)
    emb[:, 1::2] = torch.cos(pos / div)
    return emb


class EncoderBlock(nn.Module):
    def __init__(self, d_model, nhead, d_ff, dropout):
        super().__init__()
        self.attn = MultiHeadAttention(d_model=d_model, head=nhead)
        self.ff1 = nn.Linear(d_model, d_ff)
        self.ff2 = nn.Linear(d_ff, d_model)
        self.ln1 = nn.LayerNorm(d_model)
        self.ln2 = nn.LayerNorm(d_model)
        self.act = nn.ReLU()
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, pad_mask):
        x2 = self.attn(x, x, x, pad_mask)
        x = x + self.dropout(x2)
        x = self.ln1(x)
        x2 = self.ff1(x)
        x2 = self.act(x2)
        x2 = self.ff2(x2)
        x = x + self.dropout(x2)
        x = self.ln2(x)
        return x


class Encoder(nn.Module):
    def __init__(self, vocab_size, max_len, d_model=512, nhead=8, num_layers=6, d_ff=2048, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.blocks = nn.ModuleList([EncoderBlock(d_model, nhead, d_ff, dropout) for _ in range(num_layers)])
        pe = torch.zeros(max_len, d_model)
        self.register_buffer("pos", pos_encoder(pe, max_len, d_model))
        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model

    def forward(self, x, pad_mask):
        x = self.dropout(self.embedding(x) * (self.d_model ** 0.5) + self.pos[:x.size(1), :])
        for block in self.blocks:
            x = block(x, pad_mask)
        return x


class DecoderBlock(nn.Module):
    def __init__(self, max_len, d_model, nhead, d_ff, dropout):
        super().__init__()
        self.attn1 = MultiHeadAttention(d_model=d_model, head=nhead)
        self.attn2 = MultiHeadAttention(d_model=d_model, head=nhead)
        self.ff1 = nn.Linear(d_model, d_ff)
        self.ff2 = nn.Linear(d_ff, d_model)
        self.ln1 = nn.LayerNorm(d_model)
        self.ln2 = nn.LayerNorm(d_model)
        self.ln3 = nn.LayerNorm(d_model)
        self.act = nn.ReLU()
        self.register_buffer("mask", torch.triu(torch.ones(max_len, max_len), diagonal=1).bool())
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, y, src_mask, tgt_mask):
        seq = x.size(1)
        causal = self.mask[:seq, :seq].unsqueeze(0).unsqueeze(0)
        comb = causal | tgt_mask
        x2 = self.attn1(x, x, x, comb)
        x = x + self.dropout(x2)
        x = self.ln1(x)
        x2 = self.attn2(x, y, y, src_mask)
        x = x + self.dropout(x2)
        x = self.ln2(x)
        x2 = self.ff1(x)
        x2 = self.act(x2)
        x2 = self.ff2(x2)
        x = x + self.dropout(x2)
        x = self.ln3(x)
        return x


class Decoder(nn.Module):
    def __init__(self, vocab_size, max_len, d_model=512, nhead=8, num_layers=6, d_ff=2048, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.blocks = nn.ModuleList([DecoderBlock(max_len, d_model, nhead, d_ff, dropout) for _ in range(num_layers)])
        pe = torch.zeros(max_len, d_model)
        self.register_buffer("pos", pos_encoder(pe, max_len, d_model))
        self.dropout = nn.Dropout(dropout)
        self.d_model = d_model

    def forward(self, x, y, src_mask, tgt_mask):
        x = self.dropout(self.embedding(x) * (self.d_model ** 0.5) + self.pos[:x.size(1), :])
        for block in self.blocks:
            x = block(x, y, src_mask, tgt_mask)
        return x


class Transformer(nn.Module):
    def __init__(self, src_vocab, tgt_vocab, max_len, d_model=512, nhead=8, num_layers=6, d_ff=2048, dropout=0.1):
        super().__init__()
        self.enc = Encoder(src_vocab, max_len, d_model, nhead, num_layers, d_ff, dropout)
        self.dec = Decoder(tgt_vocab, max_len, d_model, nhead, num_layers, d_ff, dropout)
        self.fc = nn.Linear(d_model, tgt_vocab)

    def forward(self, src, tgt, src_mask, tgt_mask):
        enc_out = self.enc(src, src_mask)
        dec_out = self.dec(tgt, enc_out, src_mask, tgt_mask)
        return self.fc(dec_out)

# ════════════════════════════════════════════════════════════
# Cell 4 — 유틸리티 함수들
# ════════════════════════════════════════════════════════════
def make_pad_mask(seq, pad_id):
    # seq: (batch, seq_len) → (batch, 1, 1, seq_len)
    return (seq == pad_id).unsqueeze(1).unsqueeze(2)


class TransDataset(Dataset):
    def __init__(self, X, Y_input, Y_output):
        self.X = X
        self.Y_input = Y_input
        self.Y_output = Y_output

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y_input[idx], self.Y_output[idx]


def encode_data(data, tok, max_len=128):
    X, Y_input, Y_output = [], [], []
    BOS = tok.bos_token_id
    EOS = tok.eos_token_id
    for item in tqdm(data):
        src = item['translation']['de']
        tgt = item['translation']['en']
        src_enc = tok.encode(src, add_special_tokens=False)
        X.append([BOS] + src_enc[:max_len-2] + [EOS])

        tgt_enc = tok.encode(tgt, add_special_tokens=False)
        Y = [BOS] + tgt_enc[:max_len-2] + [EOS]
        Y_input.append(Y[:-1])
        Y_output.append(Y[1:])
    return X, Y_input, Y_output


def collate_fn(batch):
    x, y_in, y_out = zip(*batch)
    x     = pad_sequence([torch.tensor(s) for s in x],     batch_first=True, padding_value=PAD_ID)
    y_in  = pad_sequence([torch.tensor(s) for s in y_in],  batch_first=True, padding_value=PAD_ID)
    y_out = pad_sequence([torch.tensor(s) for s in y_out], batch_first=True, padding_value=PAD_ID)
    return x, y_in, y_out


def set_and_loader(data, tok, shuffle=True):
    X, Y_in, Y_out = encode_data(data, tok, MAX_LEN)
    dataset = TransDataset(X, Y_in, Y_out)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=shuffle, collate_fn=collate_fn)
    return dataset, dataloader


def inference(text, model, tok, max_len, device):
    model.eval()
    bos_id = tok.bos_token_id
    eos_id = tok.eos_token_id
    with torch.no_grad():
        src_enc = tok.encode(text, add_special_tokens=False)
        src = torch.tensor([bos_id] + src_enc[:max_len-2] + [eos_id]).unsqueeze(0).to(device)
        src_mask = make_pad_mask(src, tok.pad_token_id)
        enc_out = model.enc(src, src_mask)
        tgt = torch.tensor([[bos_id]]).to(device)
        for _ in range(max_len):
            tgt_mask = make_pad_mask(tgt, tok.pad_token_id)
            dec_out = model.dec(tgt, enc_out, src_mask, tgt_mask)
            selected = model.fc(dec_out[:, -1, :]).argmax(dim=-1, keepdim=True)
            tgt = torch.cat([tgt, selected], dim=1)
            if selected.item() == eos_id:
                break
    return tok.decode(tgt.squeeze().tolist(), skip_special_tokens=True)

# ════════════════════════════════════════════════════════════
# Cell 5 — 데이터 로드 (BPE + Special Tokens 추가)
# ════════════════════════════════════════════════════════════
MAX_LEN = 256
tok = AutoTokenizer.from_pretrained("google-t5/t5-base")

# BOS, EOS 토큰 정의 및 추가
special_tokens_dict = {'bos_token': '[BOS]', 'eos_token': '[EOS]', 'pad_token': '[PAD]'}
num_added_toks = tok.add_special_tokens(special_tokens_dict)

PAD_ID = tok.pad_token_id
VOCAB_SIZE = len(tok) # 추가된 토큰이 반영된 크기

train_raw = load_dataset("wmt19", "de-en", split="train[:1000000]")
val = load_dataset("wmt19", "de-en", split="validation")
val_split = val.train_test_split(test_size=0.5, seed=42)
dev_raw = val_split["train"]
test_raw = val_split["test"]

trainset, trainloader = set_and_loader(train_raw, tok, shuffle=True)
devset, devloader = set_and_loader(dev_raw, tok, shuffle=False)
testset, testloader = set_and_loader(test_raw, tok, shuffle=False)

print(f"Tokenizer: {tok.__class__.__name__} (BPE + Custom Tokens)")
print(f"Added tokens: {num_added_toks}")
print(f"Vocab Size: {VOCAB_SIZE}")
print(f"BOS ID: {tok.bos_token_id}, EOS ID: {tok.eos_token_id}")

class WarmupScheduler:
    def __init__(self, optimizer, d_model, warmup_steps=4000):
        self.optimizer = optimizer
        self.d_model = d_model
        self.warmup_steps = warmup_steps
        self.step_num = 0

    def step(self):
        self.step_num += 1
        lr = (self.d_model ** -0.5) * min(
            self.step_num ** -0.5,
            self.step_num * self.warmup_steps ** -1.5
        )
        for pg in self.optimizer.param_groups:
            pg['lr'] = lr
        self.optimizer.step()

# ════════════════════════════════════════════════════════════
# Cell 6 — 하이퍼파라미터 & 모델 초기화
# ════════════════════════════════════════════════════════════
D_MODEL    = 512
NHEAD      = 8
NUM_LAYERS = 6
D_FF       = 2048
DROPOUT    = 0.1
NUM_EPOCHS = 1
LR         = 0.5

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

# VOCAB_SIZE가 업데이트된 상태로 모델 생성
model = Transformer(
    src_vocab=VOCAB_SIZE, tgt_vocab=VOCAB_SIZE, max_len=MAX_LEN,
    d_model=D_MODEL, nhead=NHEAD, num_layers=NUM_LAYERS, d_ff=D_FF, dropout=DROPOUT
).to(device)

criterion = nn.CrossEntropyLoss(ignore_index=PAD_ID, label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=LR, betas=(0.9, 0.98), eps=1e-9)
scheduler = WarmupScheduler(optimizer, D_MODEL, warmup_steps=4000)

# ════════════════════════════════════════════════════════════
# Cell 7 — 학습 루프
# ════════════════════════════════════════════════════════════
import wandb

# 1. wandb 초기화
wandb.init(
    project="transformer-translation",
    config={
        "learning_rate": LR,
        "epochs": NUM_EPOCHS,
        "batch_size": 64,
        "d_model": D_MODEL,
        "warmup_steps": 4000,
        "save_interval": 500  # 500 스텝마다 체크포인트 확인
    }
)

min_loss = 1e9
save_interval = 500
current_step = 0

model.train()
for epoch in range(NUM_EPOCHS):
    total_loss = 0
    pbar = tqdm(enumerate(trainloader), total=len(trainloader))
    
    for i, (x, y_in, y_out) in pbar:
        x, y_in, y_out = x.to(device), y_in.to(device), y_out.to(device)
        src_mask = make_pad_mask(x, PAD_ID)
        tgt_mask = make_pad_mask(y_in, PAD_ID)
        
        outputs = model(x, y_in, src_mask, tgt_mask)
        loss = criterion(outputs.view(-1, VOCAB_SIZE), y_out.view(-1))
        
        optimizer.zero_grad()
        loss.backward()
        scheduler.step() # 주의: scheduler 내부에서 optimizer.step() 호출됨
        
        current_loss = loss.item()
        total_loss += current_loss
        current_step += 1

        # 2. wandb 로그 기록
        wandb.log({
            "train/loss": current_loss,
            "train/avg_loss": total_loss / (i + 1),
            "learning_rate": optimizer.param_groups[0]['lr'],
            "step": current_step
        })

        # 3. 일정 스텝마다 최소 Loss 갱신 및 저장
        if current_step % save_interval == 0:
            avg_step_loss = total_loss / (i + 1)
            if avg_step_loss < min_loss:
                min_loss = avg_step_loss
                torch.save(model.state_dict(), 'best_model_step.pth')
                print(f"\n[Step {current_step}] New Best Loss: {min_loss:.4f} - Model Saved!")
                wandb.run.summary["best_loss"] = min_loss

        if i % 100 == 0:
            pbar.set_postfix(loss=f"{total_loss / (i+1):.4f}")

    avg_loss = total_loss / len(trainloader)
    print(f'Epoch [{epoch+1}/{NUM_EPOCHS}] Train Loss: {avg_loss:.4f}')

    # Validation
    model.eval()
    eval_loss = 0
    with torch.no_grad():
        for x, y_in, y_out in tqdm(devloader):
            x, y_in, y_out = x.to(device), y_in.to(device), y_out.to(device)
            src_mask = make_pad_mask(x, PAD_ID)
            tgt_mask = make_pad_mask(y_in, PAD_ID)
            outputs = model(x, y_in, src_mask, tgt_mask)
            loss = criterion(outputs.view(-1, VOCAB_SIZE), y_out.view(-1))
            eval_loss += loss.item()
    avg_eval_loss = eval_loss / len(devloader)
    print(f'Epoch [{epoch+1}/{NUM_EPOCHS}] Val Loss: {avg_eval_loss:.4f}')
    wandb.log({
            "val/loss": avg_eval_loss,
        })
    # Checkpoint
    if avg_eval_loss < min_loss:
        min_loss = avg_eval_loss
        torch.save(model.state_dict(), 'weights.pth')
        print("  → Best model saved!")
wandb.finish()

# ════════════════════════════════════════════════════════════
# Cell 8 — 최종 평가 (Perplexity + BLEU)
# ════════════════════════════════════════════════════════════
model.load_state_dict(torch.load('weights.pth'))  # best model 불러오기
model.eval()

test_loss = 0
pred, target = [], []

with torch.no_grad():
    for x, y_in, y_out in tqdm(testloader):
        x, y_in, y_out = x.to(device), y_in.to(device), y_out.to(device)
        src_mask = make_pad_mask(x, PAD_ID)
        tgt_mask = make_pad_mask(y_in, PAD_ID)
        outputs = model(x, y_in, src_mask, tgt_mask)
        loss = criterion(outputs.view(-1, VOCAB_SIZE), y_out.view(-1))
        test_loss += loss.item()

avg_test_loss = test_loss / len(testloader)
perplexity = math.exp(avg_test_loss)
print(f"\n====== Final Evaluation ======")
print(f"Test Perplexity: {perplexity:.2f}")

for item in tqdm(test_raw.select(range(10))):
    src = item['translation']['de']
    tgt = item['translation']['en']
    model.eval()
    pred.append(inference(src, model, tok, MAX_LEN, device))
    target.append(tgt)


bleu = corpus_bleu(pred, [target]).score


print(f"BLEU Score:      {bleu:.2f}")

# 샘플 번역 5개 출력
print("\n====== Sample Translations ======")
for i in range(min(5, len(pred))):
    print(f"[{i}] PRD: {pred[i]}")
    print(f"    REF: {target[i]}\n")

print(tok.bos_token_id)   # 학습 때 Y_input의 첫 토큰과 같아야 함
print(tok.eos_token_id)

